tasks:
  - init: sh wasm-cloud-base/init.sh
    command: sh wasm-cloud-base/command.sh

github:
  prebuilds:
    master: true
    pullRequests: true
    addBadge: true
    branches: true

vscode:
  extensions:
    - matklad.rust-analyzer
    - serayuzgur.crates
    - vscode.rust
    - bungcip.better-toml
