# This docker-compose file loads 
#   nats with JetStream enabled
#   a local OCI registry
#   redis (for the kvredis capability provider)
#   wasmcloud_host

version: "3.2"
services:
  nats:
    image: nats:2.3
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: [ "-js" ]
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  registry:
    image: registry:2.7
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
    ports:
      - "5000:5000"
  wasmcloud:
    image: wasmcloud/wasmcloud_host:latest
    command: "/opt/app/bin/wasmcloud_host foreground"
    volumes:
      - type: bind
        source: ../
        target: $DIR
    environment:
      - WASMCLOUD_RPC_HOST=nats
      - WASMCLOUD_CTL_HOST=nats
      - WASMCLOUD_PROV_RPC_HOST=nats
      - DASHBOARD_HOST=${GP_HOST}
    ports:
      - "4000:4000"
      - "8080:8080" # Allows exposing examples on ports 8080-8089
